# Generated by Django 3.0.3 on 2020-02-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoponline', '0002_shippingdetail_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='productImage',
            field=models.ImageField(upload_to=''),
        ),
    ]
