# Generated by Django 3.0.3 on 2020-02-27 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shoponline', '0003_auto_20200227_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='createdon',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='users',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
